# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    ports:
      - '27017:27017'
    networks:
    - nestmicroservice

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
    - nestmicroservice

volumes:
  mongodb_master_data:
    driver: local

networks:
  nestmicroservice: